services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-machinehub}
      MYSQL_USER: ${MYSQL_USER:-machinehub}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - machine-hub-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build:
      context: ./machine-hub-api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - ./machine-hub-api/.env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - machine-hub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 10s
      retries: 5
      start_period: 30s

  web:
    build:
      context: ./machine-hub-web
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL:-http://localhost:8000}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - machine-hub-network

volumes:
  db-data:

networks:
  machine-hub-network:
    driver: bridge
